spring:
  application:
    name: expense-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3333/expenses
    username: root
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  config:
    import: classpath:eurekaServer.yml,redisServer.yml

server:
  port: 8004
  
management:
  tracing:
    sampling:
      probability: 1.0
 
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      authBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        register-health-indiator: true
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based

        max-attempts: 0
        wait-duration: 2s

  ratelimiter:
    instances:
      authBreaker:
        timeout-duration: 0
        limit-refresh-period: 4
        limit-for-period: 2
