spring:
  application:
    name: expense-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3333/expenses
    username: root
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
  config:
    import: classpath:eurekaServer.yml,redisServer.yml

server:
  port: 8004
  
management:
  tracing:
    sampling:
      probability: 1.0
